### ISSUE TITLE
Can't find URI for button

### ISSUE THREAD

**Issue by mebendix** [Djelibeybi/homebridge-button-platform#11]
Hi.
I have tried to setup the button-platform, but can't really get it to work. 
I have searched through the log and can't find any URI. I have set up a button called button-name. When I try to do a post to http://192.168.0.112:3001/button-name?event=click it returns with a 404.

Here's what it says in the log:
Wed, 28 Oct 2020 19:00:13 GMT finalhandler default 404
Wed, 28 Oct 2020 19:00:13 GMT body-parser:urlencoded skip empty body
Wed, 28 Oct 2020 19:00:13 GMT express:router urlencodedParser  : /button-name?event=click
Wed, 28 Oct 2020 19:00:13 GMT body-parser:json skip empty body
Wed, 28 Oct 2020 19:00:13 GMT express:router jsonParser  : /button-name?event=click
Wed, 28 Oct 2020 19:00:13 GMT express:router expressInit  : /button-name?event=click
Wed, 28 Oct 2020 19:00:13 GMT express:router query  : /button-name?event=click
Wed, 28 Oct 2020 19:00:13 GMT express:router dispatching GET /button-name?event=click

My config:
{
      "port" : "3001",
      "buttons" : [
        "button name"
      ],
      "name" : "Button Platform",
      "platform" : "button-platform"
    }

When I load homebridge this is what it says:
[10/28/2020, 7:02:38 PM] [Button Platform] Listening on port 3001 for inbound button push event notifications
[10/28/2020, 7:02:37 PM] [Button Platform] restored 2 accessories from cache
[10/28/2020, 7:02:37 PM] [Button Platform] homebridge-button-platform v1.1.5, node 11.6.0, homebridge v1.2.3, homebridge-lib v4.7.16
[10/28/2020, 7:02:37 PM] [Button Platform] Initializing button-platform platform...

I hope you can help me to get it work. Thanks in advance!

**Comment by Djelibeybi** [comment]
Look for log lines like `The Event URI for button name is: /button-button-name`. I'm fairly sure that's what the URI should be, i.e. you're not quite getting the right one.

**Comment by Djelibeybi** [comment]
It also looks like you have debug logging on, which generates a lot more noise than is necessary. I would recommend turning that off.

**Comment by mebendix** [comment]
I have tried looking through all the lines, and can't find any lines saying The Event URI for button name is: /button-button-name. But shouldn't it be accessible via http://192.168.0.112:3001/button-name ?

**Comment by Djelibeybi** [comment]
No, it shouldn't. I prefix the URI with `button-` automatically, so it would likely be `/button-button-name`. And if you can't find that log line, then it's not creating the URI correctly anyway. I've never see the rest of those logs either, which is also weird.

**Comment by Djelibeybi** [comment]
You should also be using Node.js 12 LTS for this. I notice you're only on Node.js 11. I've never tested it on that old version.

**Comment by mebendix** [comment]
Oh. I also meant http://192.168.0.112:3001/button-button-name. But I think you're right. It seems to look a bit weird. I will try to update Node. Just give me a sec

**Comment by mebendix** [comment]
I have tried updating to nodejs v12.19.0. When I open terminal and enter the command:
nodejs -v
v12.19.0

It says I'm on v12. But when I run homebridge it tells me that:
[10/28/2020, 8:13:57 PM] [Button Platform] warning: 11.6.0: not using recommended node v12.19.0 LTS

What have I done wrong?

**Comment by mebendix** [comment]
Using this I finally got it to work:

sudo npm cache clean -f
sudo npm install -g n sudo n stable
n 12.19.0
