### ISSUE TITLE
Trying to use this plugin to control a smart switch from Stream Deck. But the virtual devices don't show up in the Home app

### ISSUE THREAD

**Issue by nefariouslegion** [Djelibeybi/homebridge-button-platform#140]
Basically title.

I've installed the plugin and setup the virtual button. I can see it in the accessories page on the Homebridge UI. But the virtual button doesn't show up in HomeKit. Therefor I can't link it to anything. Unless I'm missing something?

Currently I have the button on my streamdeck setup to control the virtual button and that works. But like I said I can't seem to link the virtual button to anything since it doesn't show up in HomeKit/the Home app

**Comment by Denzii89** [comment]
I have the same problem. It doesnt  show up in the Home App. Whats the solution?
