### ISSUE TITLE
Toggle Switch

### ISSUE THREAD

**Issue by bytheedgeuk** [Djelibeybi/homebridge-button-platform#2]
Is there a way to set up a toggle switch. So rather than one click for on, double click for off. One click could know the state of a device then toggle the state?

**Comment by Djelibeybi** [comment]
Yes, HomeKit allows you to do this via conditional automations or by creating a shortcut. Which app are you using for creating your automations? The default Home app is pretty limited, so most folks either use [Eve for HomeKit](https://apps.apple.com/au/app/eve-for-homekit/id917695792) which is free or [Home+ 4](https://apps.apple.com/au/app/home-4/id995994352) which is paid.

Alternatively, with iOS 13 you can turn an automation into a Shortcut and that has conditional functionality as well.

**Comment by bytheedgeuk** [comment]
Got it, thanks. Made it work using the Eve app.

**Comment by bytheedgeuk** [comment]
I've found the best way to do this is using shortcuts with the Home app rather than use a seperate app.

**Comment by Djelibeybi** [comment]
> I've found the best way to do this is using shortcuts with the Home app rather than use a seperate app.

Intreresting. I find using HomeKit automations works best for me. Shortcuts tend to break for me if the Home Hub is a HomePod.

**Comment by metawops** [comment]
Using the "Convert To Shortcut" feature and writing a short shortcut that first checks for the Power State and then decides whether to turn on or off a switch worked for me initially. 
However, for a few days now it doesn't work anymore.
Directly switching a switch on or off still works, though.
But I use an Elgato Streamdeck to toggle-switch some lights and really don't want to use two StreamDeck buttons for one light.
What changed? Con anyone confirm that it's not working anymore?
