### ISSUE TITLE
Naive Question - linking (virtual) Button Platform switch to (actual) Homebridge switch

### ISSUE THREAD

**Issue by marana** [Djelibeybi/homebridge-button-platform#20]
Apologies in advance but I couldn't quite grok it from the instructions. How do I link one of the created "buttons" to an actual switch within Homebridge? As I add more buttons to the config list, I can see the URIs being created, but how do I associate a created button to an actual switch (e.g. Hue Lightbulb in Homebridge)?

**Comment by Djelibeybi** [comment]
You don't do that in Homebridge, you do that in the Home app. 😄 If you look at the configuration of the button there, you'll see you can add automation for each of the events. You'll need a Home Hub (like an Apple TV, HomePod or iPad) for this to work.

**Comment by marana** [comment]
got it! Thanks!

**Comment by Djelibeybi** [comment]
Keep in mind that the Flic Hub LR now has official HomeKit support, which I recommend over this plugin, if you have one.
