### ISSUE TITLE
Button not triggering the same event twice 

### ISSUE THREAD

**Issue by Cunner** [Djelibeybi/homebridge-button-platform#31]
Hello,
At first thanks for the great plug in!
I have a weird problem... 
when I try to trigger the button with a get request it for example with the “click” event it just works once and only when the prior event was not the same event type.
When I look at the log it says: “received get request to trigger a click event” but nothing happens... if I then for example chance the event to a “double-click” it again works but just for one time.
I also have an additional line in the log which says: “set Programmable switch event from 0 to 1”

is there anything I can do here ?

thanks for your support!

**Comment by Djelibeybi** [comment]
Are you using Flic or Stream Deck? If you're using a Flic, do you have a Flic Hub LR?

**Comment by Cunner** [comment]
Neither of both... for testing I just used a browser.
But I’ll use a Shelly 1 in my productive set up and want to assigne the long press function to it :-)
Does that make any difference ?

**Comment by Djelibeybi** [comment]
Oh, nifty. I love it when folks introduce new things! I'm wondering if the browser isn't the problem here, because they innately try to cache things. Can you try using `curl` instead, i.e. `curl http://<homebridge>:<port>/uri?event=click`? If repeated calls using `curl` don't work, then we may have to look deeper.

**Comment by Djelibeybi** [comment]
Nope, this is a bug. Must be something in Homebridge 1.3 that I have to adjust for.

**Comment by Cunner** [comment]
So should I switch back to a prior version then ? 
I just wanted to add some new log commands to see what gets triggered in the “switch case” sections but i looks like you found the problem 👌🏼

**Comment by Djelibeybi** [comment]
I can reproduce the issue, but I don't (yet) know what's causing it. It's something to do with the library I'm using. I'll need to look into it, so I'm not sure how long before it'll be fixed, sorry. :(

**Comment by Cunner** [comment]
Maybe is the “buttonServices.statelessProgrammableSwitch.triggerEvent(1)” somehow saving the state and just triggers an event when there appears a new event Typ 🤷🏼‍♂️
thank you!

**Comment by Djelibeybi** [comment]
Yeah, something like that.
