### ISSUE TITLE
zsh: no matches found

### ISSUE THREAD

**Issue by Jacksonbm1** [Djelibeybi/homebridge-button-platform#39]
Using terminal on my mac:

Input: `curl http://<HB-IP>:<port>/button-door-on?event=click`

Output `zsh: no matches found: http://<HB-IP>:<port>/button-door-on?event=click`

I have tested this on my web browser and the url works fine. What's going on here?

**Comment by Jacksonbm1** [comment]
Also, no logs in response to the error. Homebridge is probably just not seeing the event for some reason

**Comment by Djelibeybi** [comment]
It's `zsh` being (not very) helpful and trying to glob the question mark. Wrap the URL in double-quotes, i.e. 

```shell
$ curl "http://homebridge:3001/button-door-on?event=click"
```

**Comment by Jacksonbm1** [comment]
Thanks so much! You're quick responses are awesome!

**Comment by Djelibeybi** [comment]
> Thanks so much! You're quick responses are awesome!

You're welcome. :)
