### ISSUE TITLE
"warning: Received event for unconfigured Button path"

### ISSUE THREAD

**Issue by robhester** [Djelibeybi/homebridge-button-platform#4]
Thank you for making this! 

Are there limits on button names (characters or string limits)? I'm getting the following error:

[Button Platform] warning: Received event for unconfigured Button path: /vacuum_kitchen

and same thing, if I append "button-"

[Button Platform] warning: Received event for unconfigured Button path: /button-vacuum_kitchen

I must be missing something!

Thanks again.

**Comment by Djelibeybi** [comment]
There's no specific limit, though I believe there is a 255 character limit for URLs generally. What does your `config.json` look like? Do you have that button configured?

**Comment by robhester** [comment]
I apologize if I've not set this up correctly... below is config.json excerpt, and screenshots of my homekit/flic configs.

```
        {
            "name": "Button Platform",
            "port": 3001,
            "buttons": [
                "espresso",
                "vacuum",
                "vacuum_kitchen",
                "vacuum_living_room_A",
                "vacuum_living_room_B",
                "vacuum_living_room_all",
                "vacuum_bathroom"
            ],
            "platform": "button-platform"
        }
```

![Screenshot 2020-05-18 at 10 35 25 PM](https://user-images.githubusercontent.com/35043191/82278509-6215f780-9958-11ea-9d6e-31c7023d1c85.jpeg)
![Screenshot 2020-05-18 at 10 36 21 PM](https://user-images.githubusercontent.com/35043191/82278510-62ae8e00-9958-11ea-9859-a153c52e3cb7.jpeg)

**Comment by Djelibeybi** [comment]
No need to apologise. Check the logs for Homebridge to see what the URI is. You should be able to find a log entry for `The Event URI for vacuum_kitchen is:` and then the actual URI you should use.

Note that you can give your buttons friendlier names for HomeKit, like "Vacuum Kitchen" and the plugin will automatically turn them into valid URLs. The logs will show you the exact URI to use, or at least, it should! Let me know what the logs say.

**Comment by Djelibeybi** [comment]
The plugin also automatically prefixes the URI with `/button-` so it's likely to be something like `/button-vacuum_kitchen` but it may have changed or removed the underscore to normalise it.

**Comment by Djelibeybi** [comment]
I just ran a test and the plugin changed it to `/button-vacuum-kitchen`, so try that. :)

**Comment by Djelibeybi** [comment]
Let me know if this worked for you, so I can close this issue.

**Comment by Djelibeybi** [comment]
I'm going to close this now. If you still have any issues, please open a new issue!

**Comment by robhester** [comment]
@Djelibeybi, thank you kindly for the commentary and testing. I'm sorry for the delay in getting back to you. Your feedback was very helpful, and I've tried again - everything works as described above. I now have a flic button available to hit when I quickly want to vacuum the kitchen, thanks to you!
