### ISSUE TITLE
No reaction

### ISSUE THREAD

**Issue by M1dfsdiekfj** [Djelibeybi/homebridge-button-platform#43]
Hi there
It's a great and simple working plugin, thank you for programming. Although not being very skilled, at least I once managed to get it running completely. But out of a sudden, it doesn't work anymore. When I trigger the command (e.g. via Browser) the success is shown by the Homebridge protocol and even by the bumping button in the Home.App. The underlying scene or event actually works perfectly otherwise. Any idea what the problem might be?

**Comment by Djelibeybi** [comment]
Do you have a Home Hub like a HomePod, Apple TV 4 or dedicated iPad? If you don't, there is nothing to run the action when it's triggered.

**Comment by M1dfsdiekfj** [comment]
Everything in place (ATV 4). The weird thing is that it once worked. Even now, the button in HomeKit itself shows that it's being triggered. Only the last step – the plug being switched on or off – doesn't happen. I doesn't matter whether a scene or a smart plug should be triggered, in both cases it fails at the last step, the actual switching on or off.
But maybe the problem is in HomeKit and not in the button platform.

**Comment by Djelibeybi** [comment]
If you can see the button in HomeKit is activating, that's where its capabilities end. 

Perhaps test the same automation with a different trigger, to see if that works.

**Comment by M1dfsdiekfj** [comment]
Right now, I got it back running. Still it's not clear to me what exactly brought it back, yet it might have something to do with the (same or not) name of the button in HomeKit and Button Platform which. 
Anyway, it's running, which is great.

**Comment by Djelibeybi** [comment]
Glad you worked it out.
