### ISSUE TITLE
Renamed buttons persisting

### ISSUE THREAD

**Issue by mbriney** [Djelibeybi/homebridge-button-platform#6]
A big thank you for creating this plugin, it takes a fairly useless flic system and makes it completely usable!

I am running into an issue however.  I renamed a button using the ConfigX UI and I am now seeing two buttons show-up in my homekit UI and in the Config UI.  When I look at the config.json I don't see the values for the previously named button.  I'm guessing this is being cached somewhere in another file?

Is there another place I should be looking for to delete the older virtual buttons?

Thanks!

**Comment by Djelibeybi** [comment]
This should be fixed in v1.1.1, now available on npmjs.com. Thanks for reporting this!
