### ISSUE TITLE
Using the "Convert To Shortcut" feature 

### ISSUE THREAD

**Issue by Djelibeybi** [Djelibeybi/homebridge-button-platform#69]
Using the "Convert To Shortcut" feature and writing a short shortcut that first checks for the Power State and then decides whether to turn on or off a switch worked for me initially. 
However, for a few days now it doesn't work anymore.
Directly switching a switch on or off still works, though.
But I use an Elgato Streamdeck to toggle-switch some lights and really don't want to use two StreamDeck buttons for one light.
What changed? Con anyone confirm that it's not working anymore?

_Originally posted by @metawops in https://github.com/Djelibeybi/homebridge-button-platform/issues/2#issuecomment-899727481_

**Comment by Djelibeybi** [comment]
Here are the two automations that create a toggle for the same button push:

<img width="488" alt="Screen Shot 2021-08-17 at 8 10 16 am" src="https://user-images.githubusercontent.com/103232/129635754-ce92d4f0-1c2f-48cf-841c-43463a18d704.png">
<img width="480" alt="Screen Shot 2021-08-17 at 8 10 27 am" src="https://user-images.githubusercontent.com/103232/129635761-56e5df17-010f-4c0e-96fa-3f5ebbf84337.png">

Screenshot is from Controller for HomeKit (the macOS version).

**Comment by Djelibeybi** [comment]
You can't create conditional automations using Apple's default Home app, but you can using Eve or Home+ or Controller for HomeKit, etc.

**Comment by metawops** [comment]
Yes you can. Since iOS 13, I think. You don't need any 3rd party app anymore. It worked flawlessly for me. All of a sudden, it stopped.

**Comment by Djelibeybi** [comment]
Yeah, I'm aware of Shortcuts. They don't work that well for me either, which is why I use HomeKit automations with a condition instead. I'm not sure why your shortcut doesn't work any more though. I'll create an automation using Shortcuts to see if I can reproduce it.

**Comment by Djelibeybi** [comment]
I just tried it and it worked just fine. If you create a new automation, does that work? It may be that your HomeKit data is out of sync on your Home Hubs (especially if you have more than one).

**Comment by metawops** [comment]
Yes, I deleted and newly created this simple shortcut over and over again. It works fine when testing in the Home app, that is: it reads the power state correctly and switches the outlet correctly off or on.
But the corresponding URL for the switch (I use the IP address of the Raspi to be sure that it's not a hostname/avahi problem) does nothing.
The URL for the switch works fine when I don't use a Shortcut but instead directly the outlet and switch that on, for example. But that way I have to use two buttons on my Elgato Streamdeck. I was using one button with that small Shortcut to *toggle* the power state and it worked fine.

**Comment by metawops** [comment]
It's interesting, though, that there's nothing behind the "When:" clause in Apple Home.
<img width="521" alt="Screenshot 2021-08-17 at 21 12 19" src="https://user-images.githubusercontent.com/376090/129786694-f8bad824-344b-449e-b542-d1065398fce7.png">

**Comment by Djelibeybi** [comment]
I'm going to close this issue now. If you have any further issue, please open a new one!

**Comment by metawops** [comment]
Well, nothing changed. It still doesn't work anymore but did before. Strange. Will investigate when I have time again. 🤷‍♂️

**Comment by chrise86** [comment]
@metawops did you resolve this issue? I'm facing the same thing now.

**Comment by metawops** [comment]
> @metawops did you resolve this issue? I'm facing the same thing now.

Strange thing: it‘s working again. Magically. I didn‘t do anything. Well, I surely rebooted all the involved devices (Raspberry Pi, iPhone, iPad, even my router & WiFi AP). But I can‘t say that „thing x“ did the trick. Sorry. 🤷‍♂️

**Comment by Djelibeybi** [comment]
I've only ever found this to be an issue when the HomeKit database goes out of sync on your Home Hubs. Shutdown all but one of them and test again. If that works, slowly turn the rest back on one at a time.
