### ISSUE TITLE
via Internet

### ISSUE THREAD

**Issue by UrsLebowski** [Djelibeybi/homebridge-button-platform#80]
Hi there,

I want to trigger from outside. I filled out the link with my static fixed internet ip and released port 3001 to the homebrige. but the browser reports "no connection to the server." it works with internal homebridge ip. What did I miss?
________________________________________________________________________________________________________________
Hallo,

ich möchte von ausserhalb auslösen. Ich habe den Link mit meiner statischen festen internet-ip ausgefüllt und den Port 3001 auf die homebrige freigegeben. aber der browser meldet "keine verbindung zum server." mit internen homebridge-ip funktioniert es. Was habe ich übersehen?

LG

Urs

**Comment by Djelibeybi** [comment]
I'm not sure, but I strongly advise against this, as there is zero security or authentication of any kind, so anyone who finds this open port could start sending events. It's really only meant to be activated by local devices.
