### ISSUE TITLE
Eve App Shows Low Battery Warnings for Non-Flic Buttons

### ISSUE THREAD

**Issue by nano9g** [Djelibeybi/homebridge-button-platform#88]
It appears that the default state for all buttons is 0% battery. While this doesn't cause any warnings in Apple's Home app, the Eve app takes it upon itself to display warnings that the battery is low.

It would be nice to have the option to disable the battery service for buttons that will never be used with Flic. (Looking through the source I see I could pass a 'button-battery-level' header as part of the HTTP request, but I'd like to just remove the battery information completely.)

![Eve Low Battery](https://user-images.githubusercontent.com/11694945/145271658-b3e4abda-afe6-49fe-998f-2366f75e7e1d.png)

**Comment by Djelibeybi** [comment]
Huh, it's not supposed to add a battery level unless it gets one from the Flic. I'll take a look and get it fixed. When did it start happening?

**Comment by Djelibeybi** [comment]
Should be fixed in 1.5.1. Batteries are now explicity set to 100% when Homebridge starts.

**Comment by nano9g** [comment]
That fixed it, thank you!

**Comment by Djelibeybi** [comment]
You're welcome, thanks for the report.
