### ISSUE TITLE
Platform is issuing warning: heartbeat drift errors

### ISSUE THREAD

**Issue by MoTechnicalities** [Djelibeybi/homebridge-button-platform#92]
Button platform is logging the following type of errors:

> [15/12/2021, 19:25:27] [Button Platform] warning: heartbeat 0, drift 485

> [15/12/2021, 19:25:37] [Button Platform] warning: heartbeat 9, drift 558

**Comment by Djelibeybi** [comment]
Yep. It's something the library I use does that I can't disable or suppress. The plugin doesn't use the heartbeat so it can be ignored.
