### ISSUE TITLE
Battery status present even without Flick button

### ISSUE THREAD

**Issue by mrmay-dev** [Djelibeybi/homebridge-button-platform#98]
Hi there, 

I don't own a Flick button but the plugin still adds a battery accessory. I guess it thinks I'm using one. This is my config, what else would you need to trouble-shoot this?

`        {
            "name": "Button Platform",
            "port": 3001,
            "buttons": [
                "Office Button"
            ],
            "platform": "button-platform"
        }`

Thank you for the work! I find this plugin very useful. I try to program a few things in Python and appreciate how much goes into even simple apps. So, thank you. :)

**Comment by Djelibeybi** [comment]
Is the battery status a problem? It should be set to 100% in the absence of actual Flic data.

**Comment by mrmay-dev** [comment]
Not really. I hide it easily enough. :)

Definitely on the benign side of problems. LOL
